"""
# File: exc/codes.py
# Description: This module defines error codes for exceptions in the database server.
"""

QUERY_LENGTH = "QUERY_LENGTH"
UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
DATABASE_ALREADY_EXIST = "DATABASE_ALREADY_EXIST"
INVALID_CONFIG_JSON_FILE = "INVALID_CONFIG_JSON_FILE"
