"""
# File: exc/codes.py
# Description: This module defines error codes for exceptions in the database server.
"""

QUERY_LENGTH = "QUERY_LENGTH"
UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
DATABASE_ALREADY_EXIST = "DATABASE_ALREADY_EXIST"
TABLE_ALREADY_EXIST = "TABLE_ALREADY_EXIST"
DATABASE_DOES_NOT_EXIST = "DATABASE_DOES_NOT_EXIST"
TABLE_DOES_NOT_EXIST = "TABLE_DOES_NOT_EXIST"
INVALID_CONFIG_JSON_FILE = "INVALID_CONFIG_JSON_FILE"
TABLE_NOT_PROVIDED = "TABLE_NOT_PROVIDED"
FIELD_TYPE_NOT_AVAILABLE = "FIELD_TYPE_NOT_AVAILABLE"
FIELD_VALIDATION = "FIELD_VALIDATION"
FIELD_VALIDATION_VALUE = "FIELD_VALIDATION_VALUE"
TABLE_SCHEMA_NOT_EXIST = "TABLE_SCHEMA_NOT_EXIST"
